databases:
  - name: dbreal
    databaseName: dbreal
    user: kagis
    ipAllowList: []

services:
  - type: web
    name: rails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dbreal
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  